services:
  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_PORT=27017
    networks:
      - app_network

  # NestJS Backend Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/library
      - PORT=3000
      - CORS_ORIGIN=http://localhost:3001
    depends_on:
      - mongo
    networks:
      - app_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  # React Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    environment:
      - API_URL=http://backend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

# Define named volumes for data persistence
volumes:
  mongodb_data: 

networks:
  app_network:
    driver: bridge # Use the default bridge driver
